/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: src/sanity/extract.json
export type RentalPage = {
  _id: string;
  _type: "rentalPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  headline?: LocaleString;
  intro?: LocaleText;
  included?: Array<{
    title?: LocaleString;
    body?: LocaleText;
    _type: "includedItem";
    _key: string;
  }>;
  formIntro?: LocaleText;
  quote?: {
    text?: LocaleText;
    author?: string;
    organisation?: string;
  };
};

export type LocaleText = {
  _type: "localeText";
  cs?: string;
  en?: string;
};

export type LocaleString = {
  _type: "localeString";
  cs?: string;
  en?: string;
};

export type PersonReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "person";
};

export type VenuePage = {
  _id: string;
  _type: "venuePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  statement?: LocaleText;
  intro?: LocaleBlockContent;
  founders?: Array<
    {
      _key: string;
    } & PersonReference
  >;
  motto?: LocaleString;
  infoCards?: Array<{
    title?: LocaleString;
    headline?: LocaleString;
    body?: LocaleText;
    link?: {
      label?: LocaleString;
      href?: string;
    };
    highlight?: boolean;
    _type: "infoCard";
    _key: string;
  }>;
};

export type LocaleBlockContent = {
  _type: "localeBlockContent";
  cs?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h3";
    listItem?: never;
    markDefs?: Array<{
      href: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  en?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h3";
    listItem?: never;
    markDefs?: Array<{
      href: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Settings = {
  _id: string;
  _type: "settings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroSentence?: LocaleHeroSentence;
  rentalBand?: {
    title?: LocaleString;
    text?: LocaleText;
  };
  address?: {
    street?: string;
    district?: string;
    postalCode?: string;
    city?: string;
    googleMapsUrl?: string;
  };
  mapImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: LocaleString;
    _type: "image";
  };
  email?: string;
  phone?: string;
  openingHours?: LocaleText;
  socials?: {
    instagram?: string;
    spotify?: string;
    whatsapp?: string;
  };
  mailchimpListId?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type LocaleHeroSentence = {
  _type: "localeHeroSentence";
  cs?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      category: "hudba" | "divadlo" | "tanec" | "lekce";
      _type: "categoryPill";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  en?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      category: "hudba" | "divadlo" | "tanec" | "lekce";
      _type: "categoryPill";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type Playlist = {
  _id: string;
  _type: "playlist";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  month: string;
  title?: LocaleString;
  spotifyUrl: string;
  trackCount?: number;
  cover?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: LocaleString;
    _type: "image";
  };
  tracks?: Array<{
    title: string;
    artist: string;
    url?: string;
    _type: "track";
    _key: string;
  }>;
};

export type SpaceReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "space";
};

export type Course = {
  _id: string;
  _type: "course";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: LocaleString;
  slug: LocaleSlug;
  focus?: "tanec" | "hudba" | "pohyb";
  audienceTags?: Array<string>;
  level?: LocaleString;
  lecturer?: PersonReference;
  space?: SpaceReference;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: LocaleString;
    _type: "image";
  };
  slots: Array<{
    weekday: 1 | 2 | 3 | 4 | 5 | 6 | 7;
    startTime: string;
    endTime: string;
    _type: "slot";
    _key: string;
  }>;
  runStart?: string;
  runEnd?: string;
  lessonsCount?: number;
  lessonDates?: Array<{
    date: string;
    isTrial?: boolean;
    _type: "lessonDate";
    _key: string;
  }>;
  coursePrice?: number;
  bookingUrl: string;
  allowSingleLesson?: boolean;
  singleLessonPrice?: number;
  singleLessonBookingUrl?: string;
  trialPrice?: number;
  capacity?: number;
  placesLeft?: number;
  description?: LocaleBlockContent;
  forWhom?: LocaleText;
  whatToBring?: LocaleText;
  goodToKnow?: Array<
    {
      _key: string;
    } & LocaleString
  >;
};

export type Person = {
  _id: string;
  _type: "person";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  role?: LocaleString;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: LocaleString;
    _type: "image";
  };
  bio?: LocaleText;
};

export type LocaleSlug = {
  _type: "localeSlug";
  cs?: Slug;
  en?: Slug;
};

export type Event = {
  _id: string;
  _type: "event";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: LocaleString;
  slug: LocaleSlug;
  startsAt: string;
  doorsAt?: string;
  endsAt?: string;
  hall?: SpaceReference;
  categories: Array<string>;
  heroImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: LocaleString;
    _type: "image";
  };
  lead?: LocaleText;
  body?: LocaleBlockContent;
  goodToKnow?: Array<
    {
      _key: string;
    } & LocaleString
  >;
  priceText?: LocaleString;
  ticketUrl?: string;
  capacityNote?: LocaleString;
  links?: {
    spotify?: string;
    website?: string;
  };
  featured?: boolean;
  tickerText?: LocaleString;
};

export type Space = {
  _id: string;
  _type: "space";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: LocaleString;
  capacity?: number;
  area?: number;
  features?: LocaleString;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: LocaleString;
    _type: "image";
  };
  rentable?: boolean;
  order?: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | RentalPage
  | LocaleText
  | LocaleString
  | PersonReference
  | VenuePage
  | LocaleBlockContent
  | SanityImageAssetReference
  | Settings
  | SanityImageCrop
  | SanityImageHotspot
  | LocaleHeroSentence
  | Playlist
  | SpaceReference
  | Course
  | Person
  | LocaleSlug
  | Event
  | Space
  | Slug
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/lib/queries.ts
// Variable: LAYOUT_QUERY
// Query: {  "settings": *[_id == "settings"][0]{    address, email, phone, socials, openingHours  },  "playlist": *[_type == "playlist" && month <= $month] | order(month desc)[0]{    month, title, spotifyUrl, trackCount, tracks[]{ _key, title, artist, url },    cover{ asset, hotspot, crop, alt, "lqip": asset->metadata.lqip, "dimensions": asset->metadata.dimensions }  },  "today": *[_type == "event" && startsAt >= $dayStart && startsAt < $dayEnd] | order(startsAt asc)[0]{    title, slug, startsAt, ticketUrl, "hall": hall->name  }}
export type LAYOUT_QUERY_RESULT = {
  settings:
    | {
        address: null;
        email: null;
        phone: null;
        socials: null;
        openingHours: null;
      }
    | {
        address: {
          street?: string;
          district?: string;
          postalCode?: string;
          city?: string;
          googleMapsUrl?: string;
        } | null;
        email: string | null;
        phone: string | null;
        socials: {
          instagram?: string;
          spotify?: string;
          whatsapp?: string;
        } | null;
        openingHours: LocaleText | null;
      }
    | null;
  playlist: {
    month: string;
    title: LocaleString | null;
    spotifyUrl: string;
    trackCount: number | null;
    tracks: Array<{
      _key: string;
      title: string;
      artist: string;
      url: string | null;
    }> | null;
    cover: {
      asset: SanityImageAssetReference | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
      alt: LocaleString | null;
      lqip: string | null;
      dimensions: SanityImageDimensions | null;
    } | null;
  } | null;
  today: {
    title: LocaleString | null;
    slug: LocaleSlug;
    startsAt: string;
    ticketUrl: string | null;
    hall: LocaleString | null;
  } | null;
};

// Source: src/sanity/lib/queries.ts
// Variable: HOME_QUERY
// Query: {  "settings": *[_id == "settings"][0]{    heroSentence, rentalBand, address,    mapImage{ asset, hotspot, crop, alt, "lqip": asset->metadata.lqip, "dimensions": asset->metadata.dimensions }  },  "upcoming": *[_type == "event" && ((defined(endsAt) && endsAt > $now) || (!defined(endsAt) && startsAt >= $dayStart))] | order(startsAt asc)[0...30]{   _id, title, slug, startsAt, categories, featured, priceText, tickerText, ticketUrl,  "hall": hall->name,  heroImage{ asset, hotspot, crop, alt, "lqip": asset->metadata.lqip, "dimensions": asset->metadata.dimensions } },  "courses": *[_type == "course"    && (!defined(runStart) || runStart <= $weekEnd)    && (!defined(runEnd) || runEnd >= $weekStart)  ]{ _id, title, slug, focus, slots[]{ _key, weekday, startTime, endTime } }}
export type HOME_QUERY_RESULT = {
  settings:
    | {
        heroSentence: null;
        rentalBand: null;
        address: null;
        mapImage: null;
      }
    | {
        heroSentence: LocaleHeroSentence | null;
        rentalBand: {
          title?: LocaleString;
          text?: LocaleText;
        } | null;
        address: {
          street?: string;
          district?: string;
          postalCode?: string;
          city?: string;
          googleMapsUrl?: string;
        } | null;
        mapImage: {
          asset: SanityImageAssetReference | null;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
          alt: LocaleString | null;
          lqip: string | null;
          dimensions: SanityImageDimensions | null;
        } | null;
      }
    | null;
  upcoming: Array<{
    _id: string;
    title: LocaleString | null;
    slug: LocaleSlug;
    startsAt: string;
    categories: Array<string>;
    featured: boolean | null;
    priceText: LocaleString | null;
    tickerText: LocaleString | null;
    ticketUrl: string | null;
    hall: LocaleString | null;
    heroImage: {
      asset: SanityImageAssetReference | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
      alt: LocaleString | null;
      lqip: string | null;
      dimensions: SanityImageDimensions | null;
    };
  }>;
  courses: Array<{
    _id: string;
    title: LocaleString | null;
    slug: LocaleSlug;
    focus: "hudba" | "pohyb" | "tanec" | null;
    slots: Array<{
      _key: string;
      weekday: 1 | 2 | 3 | 4 | 5 | 6 | 7;
      startTime: string;
      endTime: string;
    }>;
  }>;
};

// Query TypeMap
declare global {
  interface SanityQueries {
    '{\n  "settings": *[_id == "settings"][0]{\n    address, email, phone, socials, openingHours\n  },\n  "playlist": *[_type == "playlist" && month <= $month] | order(month desc)[0]{\n    month, title, spotifyUrl, trackCount, tracks[]{ _key, title, artist, url },\n    cover{ asset, hotspot, crop, alt, "lqip": asset->metadata.lqip, "dimensions": asset->metadata.dimensions }\n  },\n  "today": *[_type == "event" && startsAt >= $dayStart && startsAt < $dayEnd] | order(startsAt asc)[0]{\n    title, slug, startsAt, ticketUrl, "hall": hall->name\n  }\n}': LAYOUT_QUERY_RESULT;
    '{\n  "settings": *[_id == "settings"][0]{\n    heroSentence, rentalBand, address,\n    mapImage{ asset, hotspot, crop, alt, "lqip": asset->metadata.lqip, "dimensions": asset->metadata.dimensions }\n  },\n  "upcoming": *[_type == "event" && ((defined(endsAt) && endsAt > $now) || (!defined(endsAt) && startsAt >= $dayStart))] | order(startsAt asc)[0...30]{ \n  _id, title, slug, startsAt, categories, featured, priceText, tickerText, ticketUrl,\n  "hall": hall->name,\n  heroImage{ asset, hotspot, crop, alt, "lqip": asset->metadata.lqip, "dimensions": asset->metadata.dimensions }\n },\n  "courses": *[_type == "course"\n    && (!defined(runStart) || runStart <= $weekEnd)\n    && (!defined(runEnd) || runEnd >= $weekStart)\n  ]{ _id, title, slug, focus, slots[]{ _key, weekday, startTime, endTime } }\n}': HOME_QUERY_RESULT;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
